services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    environment:
      MONGO_URI: mongodb://mongo:27017/yourdbname
      REDIS_HOST: redis
      REDIS_PORT: 6379

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/project_eve

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  mongo-data:
