version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}" # Usando a variável PORT do .env
    depends_on:
      - postgres
      - redis
    env_file:
      - .env # Arquivo contendo as variáveis de ambiente
    environment:
      PROJECT_EVE_IS_PRODUCTION: ${PROJECT_EVE_IS_PRODUCTION}
      PROJECT_EVE_APP_SECRET: ${PROJECT_EVE_APP_SECRET}
      PROJECT_EVE_REDIS_URL: ${PROJECT_EVE_REDIS_URL}
      PROJECT_EVE_REDIS_PORT: ${PROJECT_EVE_REDIS_PORT}
      PROJECT_EVE_DB_USER: ${PROJECT_EVE_DB_USER}
      PROJECT_EVE_DB_PASS: ${PROJECT_EVE_DB_PASS}
      PROJECT_EVE_DB_HOST: ${PROJECT_EVE_DB_HOST}
      PROJECT_EVE_DB_DEV_DB_NAME: ${PROJECT_EVE_DB_DEV_DB_NAME}
      PROJECT_EVE_DB_TEST_DB_NAME: ${PROJECT_EVE_DB_TEST_DB_NAME}
      PROJECT_EVE_DB_PROD_DB_NAME: ${PROJECT_EVE_DB_PROD_DB_NAME}

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${PROJECT_EVE_DB_USER}
      POSTGRES_PASSWORD: ${PROJECT_EVE_DB_PASS}
      POSTGRES_DB: ${PROJECT_EVE_DB_DEV_DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "${PROJECT_EVE_REDIS_PORT}:${PROJECT_EVE_REDIS_PORT}"

volumes:
  postgres-data:
